window.PVD_DATA = {
  event: {
    name: "Aniversario PVD U.Z. Huancavelica 2026",
    institution: "Prov\u00edas Descentralizado - Unidad Zonal Huancavelica",
    shortInstitution: "PVD U.Z. Huancavelica",
    date: "2026-08-15",
    displayDate: "15 de agosto de 2026",
    sport: "Fulbito",
    venue: "Cancha principal",
    description:
      "P\u00e1gina temporal para difundir el aniversario institucional y el campeonato de fulbito.",
  },

  teams: [
    { id: "A1", name: "Equipo 01", group: "A", initials: "A1", delegate: "Delegado por confirmar", color: "Rojo", active: true },
    { id: "A2", name: "Equipo 02", group: "A", initials: "A2", delegate: "Delegado por confirmar", color: "Azul", active: true },
    { id: "A3", name: "Equipo 03", group: "A", initials: "A3", delegate: "Delegado por confirmar", color: "Negro", active: true },
    { id: "A4", name: "Equipo 04", group: "A", initials: "A4", delegate: "Delegado por confirmar", color: "Dorado", active: true },
    { id: "A5", name: "Equipo 05", group: "A", initials: "A5", delegate: "Delegado por confirmar", color: "Vino", active: true },
    { id: "B1", name: "Equipo 06", group: "B", initials: "B1", delegate: "Delegado por confirmar", color: "Rojo", active: true },
    { id: "B2", name: "Equipo 07", group: "B", initials: "B2", delegate: "Delegado por confirmar", color: "Azul", active: true },
    { id: "B3", name: "Equipo 08", group: "B", initials: "B3", delegate: "Delegado por confirmar", color: "Negro", active: true },
    { id: "B4", name: "Equipo 09", group: "B", initials: "B4", delegate: "Delegado por confirmar", color: "Dorado", active: true },
    { id: "B5", name: "Equipo 10", group: "B", initials: "B5", delegate: "Delegado por confirmar", color: "Vino", active: true },
  ],

  matches: [
    {
      id: "A01",
      phase: "Grupo A",
      round: "Fecha 1",
      date: "2026-08-15",
      time: "09:00",
      court: "Cancha principal",
      homeTeamId: "A1",
      awayTeamId: "A2",
      homeGoals: null,
      awayGoals: null,
      status: "scheduled",
      note: "",
    },
    {
      id: "A02",
      phase: "Grupo A",
      round: "Fecha 1",
      date: "2026-08-15",
      time: "09:40",
      court: "Cancha principal",
      homeTeamId: "A3",
      awayTeamId: "A4",
      homeGoals: null,
      awayGoals: null,
      status: "scheduled",
      note: "",
    },
    {
      id: "B01",
      phase: "Grupo B",
      round: "Fecha 1",
      date: "2026-08-15",
      time: "10:20",
      court: "Cancha principal",
      homeTeamId: "B1",
      awayTeamId: "B2",
      homeGoals: 1,
      awayGoals: 0,
      status: "live",
      note: "Partido en desarrollo",
    },
    {
      id: "B02",
      phase: "Grupo B",
      round: "Fecha 1",
      date: "2026-08-15",
      time: "11:00",
      court: "Cancha principal",
      homeTeamId: "B3",
      awayTeamId: "B4",
      homeGoals: null,
      awayGoals: null,
      status: "scheduled",
      note: "",
    },
    {
      id: "A03",
      phase: "Grupo A",
      round: "Fecha 2",
      date: "2026-08-15",
      time: "11:40",
      court: "Cancha principal",
      homeTeamId: "A5",
      awayTeamId: "A1",
      homeGoals: 2,
      awayGoals: 2,
      status: "finished",
      note: "Resultado confirmado",
    },
    {
      id: "B03",
      phase: "Grupo B",
      round: "Fecha 2",
      date: "2026-08-15",
      time: "",
      court: "Cancha principal",
      homeTeamId: "B5",
      awayTeamId: "B1",
      homeGoals: null,
      awayGoals: null,
      status: "suspended",
      note: "Reprogramaci\u00f3n pendiente",
    },
    {
      id: "A04",
      phase: "Grupo A",
      round: "Fecha 2",
      date: "2026-08-15",
      time: "",
      court: "Cancha principal",
      homeTeamId: "A2",
      awayTeamId: "A4",
      homeGoals: 3,
      awayGoals: 0,
      status: "walkover",
      note: "Ausencia confirmada",
    },
    {
      id: "FF01",
      phase: "Fase final",
      round: "Final",
      date: "2026-08-15",
      time: "",
      court: "Cancha principal",
      homeLabel: "1.\u00ba Grupo A",
      awayLabel: "1.\u00ba Grupo B",
      homeInitials: "1A",
      awayInitials: "1B",
      homeGoals: null,
      awayGoals: null,
      status: "scheduled",
      statusLabel: "Por definir",
      note: "Horario por confirmar",
      highlight: true,
    },
  ],

  finalStage: {
    semifinals: [
      { id: "SF1", label: "Semifinal 1", home: "1.\u00ba Grupo A", away: "2.\u00ba Grupo B", homeGoals: null, awayGoals: null },
      { id: "SF2", label: "Semifinal 2", home: "1.\u00ba Grupo B", away: "2.\u00ba Grupo A", homeGoals: null, awayGoals: null },
    ],
    final: { id: "F", label: "Final", home: "Ganador 1", away: "Ganador 2", homeGoals: null, awayGoals: null },
    thirdPlace: { id: "TP", label: "Tercer lugar", home: "Perdedor 1", away: "Perdedor 2", homeGoals: null, awayGoals: null },
    podium: {
      champion: "Por definir",
      runnerUp: "Por definir",
      thirdPlace: "Por definir",
    },
  },

  rules: {
    scoring: { win: 3, draw: 1, loss: 0 },
    tiebreakers: [
      "Mayor puntaje",
      "Mejor diferencia de goles",
      "Mayor cantidad de goles a favor",
      "Resultado directo entre equipos empatados",
      "Menor cantidad de sanciones, si se registra",
      "Decisi\u00f3n del comit\u00e9 organizador",
    ],
  },

  admin: {
    username: "Jhon.Admin",
    password: "01234567890",
    storage: {
      mode: "local-json",
      label: "Local + respaldo JSON",
      description: "Base lista para publicar en GitHub Pages y conectar luego Google Sheets/Apps Script.",
      publicSourceUrl: "",
      writeEndpointUrl: "",
    },
    summary: {
      totalTeams: 10,
      estimatedMatches: 24,
    },
    modules: [
      {
        key: "teams",
        title: "Gestionar equipos",
        description: "Crear, editar grupo, delegado, iniciales y estado.",
        action: "Abrir equipos",
      },
      {
        key: "matches",
        title: "Editar fixture",
        description: "Asignar fecha, hora, cancha, fase y enfrentamientos.",
        action: "Abrir fixture",
      },
      {
        key: "matches",
        title: "Actualizar resultados",
        description: "Cargar goles, estado de partido, W.O. o suspensi\u00f3n.",
        action: "Abrir resultados",
      },
      {
        key: "finals",
        title: "Fase final",
        description: "Definir semifinales, tercer lugar, final y podio.",
        action: "Abrir fase final",
      },
      {
        key: "backup",
        title: "Respaldo y sincronizaci\u00f3n",
        description: "Exportar, pegar/importar JSON y preparar la publicaci\u00f3n en GitHub Pages.",
        action: "Abrir respaldo",
      },
    ],
  },
};

document.documentElement.dataset.pvdData = "ready";
